import '../../../common/definations.dart';

const imageAssetsRes =
    '''// ignore_for_file: avoid_field_initializers_in_const_classes
///This file is automatically generated.
///DO NOT EDIT, all your changes would be lost.
///flutter pub run module_generator:generate_asset [customer, staff]
part of 'assets.dart';

class ImageAssets {
  ImageAssets();$contentKey
}
''';
